version: '3.1'

services:
  db:
    image: mysql:8.0.36
    container_name: mysqldb
    restart: unless-stopped
    env_file: ./.env
    environment:
      MYSQL_DATABASE : $MYSQLDB_DATABASE
      MYSQLDB_USER : $MYSQLDB_USER
      MYSQL_ROOT_PASSWORD : $MYSQLDB_ROOT_PASSWORD
    ports:
      - "$MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT"
    command: --innodb-redo-log-capacity=10485760
  app:
    depends_on:
      - db
    image: online-book-store
    restart: on-failure
    build: .
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
      - $DEBUG_PORT:$DEBUG_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url" : "jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE",
        "spring.datasource.username" : "$MYSQLDB_USER",
        "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQLDialect",
        "spring.jpa.hibernate.ddl-auto" : "validate"
      }'
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
