---
blank_issues_enabled: false
contact_links:
  - name: BookWorld: Online Book Store Community Support
    url: https://github.com/IvanovYurii/online-book-store/discussions
    about: Please ask and answer questions here.
